name: Microservices Build docker hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          
      # Construccion de jars
      - name: Build Micro Client
        run: mvn -f MicroserviceClient/pom.xml clean install -DskipTests=true
      
      - name: Build Micro Item
        run: mvn -f MIcroserviceItem/pom.xml clean install -DskipTests=true

      - name: Build Micro Config
        run: mvn -f MicroserviceConfig/pom.xml clean install -DskipTests=true

      - name: Build Micro Eureka
        run: mvn -f MicroserviceEureka/pom.xml clean install -DskipTests=true


      # Construccion de imagenes
      - name: Build image Client
        run: docker build -t ${{ secrets.DOCKER_USERNAME1 }}/mes:client .
        working-directory: MicroserviceClient
        
      - name: Build image config
        run: docker build -t ${{ secrets.DOCKER_USERNAME1 }}/mes:config .
        working-directory: MicroserviceConfig
        
      - name: Build image eureka
        run: docker build -t ${{ secrets.DOCKER_USERNAME1 }}/mes:eureka .
        working-directory: MicroserviceEureka

      - name: Build image item
        run: docker build -t ${{ secrets.DOCKER_USERNAME1 }}/mes:item .
        working-directory: MIcroserviceItem


      #Login docker
      - name: Log in to Docker Hub 
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME1 }}
          password: ${{ secrets.DOCKER_PASSWORD1 }}


        
      #Envio de imagenes a docker hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME1 }}/mes:client
          docker push ${{ secrets.DOCKER_USERNAME1 }}/mes:config
          docker push ${{ secrets.DOCKER_USERNAME1 }}/mes:eureka
          docker push ${{ secrets.DOCKER_USERNAME1 }}/mes:item
